### PR TITLE
Test PR for failing Hound/Rubocop config

### PR DESCRIPTION
**Pull request by rahim**
I'm hoping this might shed some light on some problems I'm seeing in a private repository (from which I've copied the Hound config).

After moving to inherited rubocop rules I'm seeing an unspecified Hound check failure on all PRs.

The only other change we've recently made is adding in `TargetRubyVersion`.

### CODE REVIEW

**Comment by rahim** [comment]
@teoljungberg sorry to bother you, would you be able to let me know Hound's result here?

**Comment by rahim** [comment]
Ignore my comment above, I can see Hound has succeeded :/

**Comment by rahim** [comment]
OK, now I have consistent behaviour, I forgot I needed to feed Hound some new ruby within the PR.

@teoljungberg are you able to shed any light on what's failing here?

**Comment by teoljungberg** [comment]
@rahim Please open an issue on [Hound](https://github.com/houndci/hound) itself

**Pull request closed without merging**
